https://server110.herokuapp.com/

GET http://localhost:4000/2

####

POST https://server110.herokuapp.com/create_user
Content-Type: application/json

{
    "name": "Ash",
    "email": "ash@gmail.com"
}

###

POST http://localhost:4000/
Content-Type: application/json

{
    "name": "Ash",
    "email": "ash@gmail.com",
    "password": 12345678
}

###

POST http://loccreate_useralhost:4000/
Content-Type: application/json

###
GET https://server110.herokuapp.com/all_user

###
GET https://server110.herokuapp.com/user/60da942837e54c1c5437b9d2